import { Credits } from './credits.model';
import { Instructions } from './instructions.model';
import { Sections } from './sections.model';
import { Tag } from './tag.model';
import { Compilations } from './compilations.model';
import { UserRating } from './user_ratings.model';
import { Show } from './show.model';
import { Nutrition } from './nutrition.model';
import { TotalTimeTier } from './totalTimeTier.model';
import { Renditions } from './renditions.model';

export class Recipes {
  yields: string;
  credit: Credits;
  created_at: Date;
  draft_status: string;
  language: string;
  servings_noun_singular: string;
  thumbnail_url: string;
  inspired_by_url: string;
  prep_time_minutes: number;
  updated_at: Date;
  cook_time_minutes: number;
  total_time_minutes: number;
  brand: string;
  instructions: Array<Instructions>;
  promotion: string;
  sections: Array<Sections>;
  tags: Array<Tag>;
  original_video_url: string;
  video_ad_content: string;
  brand_id: number;
  country: string;
  compilations: Array<Compilations>;
  canonical_id: string;
  slug: string;
  facebook_posts: [];
  is_one_top: boolean;
  is_shoppable: Boolean;
  seo_title: string;
  servings_noun_plural: string;
  show_id: number;
  keywords: string;
  name: string;
  num_servings: number;
  approved_at: Date;
  aspect_ratio: string;
  beauty_url: string;
  description: string;
  id: number;
  video_url: string;
  nutrition_visibility: string;
  user_ratings: UserRating;
  show: Show;
  nutrition: Nutrition;
  buzz_id: number;
  tips_and_ratings_enabled: boolean;
  video_id: number;
  total_time_tier: TotalTimeTier;
  renditions: Array<Renditions>;
}
